# Generated by Django 2.2 on 2021-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=10)),
                ('team2', models.CharField(max_length=10)),
                ('toss_winner', models.CharField(max_length=10)),
                ('toss_decision', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('dl_applied', models.CharField(max_length=10)),
                ('winner', models.CharField(max_length=10, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=10)),
                ('umpire1', models.CharField(max_length=10, null=True)),
                ('umpire2', models.CharField(max_length=10, null=True)),
                ('umpire3', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
